<a href="https://colab.research.google.com/github/Chasith-Randima/PyTorch_Course/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello world...")

Hello world...


In [ ]:
!nvidia-smi

Wed Jan 18 04:51:25 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   69C    P0    32W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import torch
import pandas as pd
import matplotlib.pyplot  as plt
import numpy as np

print(torch.__version__)

1.13.1+cu116


In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])

In [ ]:
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
# vector.item()

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
MATRIX[0]

tensor([7, 8])

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX[0][0]

tensor(7)

In [ ]:
# TENSOR

In [ ]:
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0][2][2]

tensor(9)

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5095, 0.5093, 0.9374, 0.4135],
        [0.3535, 0.7805, 0.8988, 0.8384],
        [0.5201, 0.8246, 0.4469, 0.6997]])

In [ ]:
random_tensor = torch.rand(2,4)
random_tensor

tensor([[0.7192, 0.9533, 0.2751, 0.9851],
        [0.1052, 0.9370, 0.0113, 0.4274]])

In [ ]:
random_tensor = torch.rand(3,3)
random_tensor

tensor([[0.3396, 0.6997, 0.7720],
        [0.6902, 0.7639, 0.2822],
        [0.1258, 0.2777, 0.3798]])

In [ ]:
random_tensor = torch.rand(1)
random_tensor

tensor([0.7614])

In [ ]:
random_tensor = torch.rand(1,2)
random_tensor

tensor([[0.5985, 0.4767]])

In [ ]:
random_tensor = torch.rand([1,1])
random_tensor

tensor([[0.5110]])

In [ ]:
random_tensor = torch.rand(2,2)

In [ ]:
random_tensor

tensor([[0.9906, 0.3319],
        [0.3216, 0.2250]])

In [ ]:
random_tensor = torch.rand(1,2,2)
random_tensor

tensor([[[0.0477, 0.1754],
         [0.0395, 0.9116]]])

In [ ]:
random_tensor = torch.rand(2,2,2)
random_tensor

tensor([[[0.1263, 0.1906],
         [0.8175, 0.4753]],

        [[0.8161, 0.2639],
         [0.5771, 0.0994]]])

In [ ]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
zeros = torch.zeros(size=(2,2,2))
zeros

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [ ]:
random_tensor = random_tensor[0] * zeros
random_tensor

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [ ]:
ones = torch.ones(size=(2,2))
ones

tensor([[1., 1.],
        [1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
range = torch.arange(1,10)
range


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
step = torch.arange(start=0,end=1000,step = 50)
step

tensor([  0,  50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 550, 600, 650,
        700, 750, 800, 850, 900, 950])

In [ ]:
range_like_zeroes = torch.zeros_like(input=range)
range_like_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad= False
                               )
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=torch.float64,
                               device=None,
                               requires_grad= False
                               )
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [ ]:
float_32_tensor.dtype

torch.float64

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad= False
                               )
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_32_tensor = float_32_tensor.type(torch.float16)
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_32_tensor.device

device(type='cpu')

In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 100

tensor([100, 200, 300])

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
tensor-10

tensor([-9, -8, -7])

In [ ]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor,100)

tensor([101, 102, 103])

In [ ]:
torch.sub(tensor,10)

tensor([-9, -8, -7])

In [ ]:
torch.div(tensor,10)

tensor([0.1000, 0.2000, 0.3000])

In [ ]:
tensor = tensor - 10

In [ ]:
tensor

tensor([-9, -8, -7])

In [ ]:
tensor = tensor + 10

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
torch.matmul(tensor,torch.tensor([2,3,4]))

tensor(20)

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
torch.matmul(tensor,tensor)

tensor(14)

In [ ]:
tensor_b = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])

In [ ]:
tensor_b.shape

torch.Size([3, 2])

In [ ]:
tensor_b.T,tensor_b.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), torch.Size([2, 3]))

In [ ]:
tensor_a = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])

In [ ]:
tensor_a.shape,tensor_b.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [ ]:
tensor_a.T,tensor_a.shape

(tensor([[1, 3, 5],
         [2, 4, 6]]), torch.Size([3, 2]))

In [ ]:
tensor_b.T,tensor_b.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), torch.Size([3, 2]))

In [ ]:
tensor_a

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [ ]:
torch.matmul(tensor_a,tensor_b.T),tensor_a.shape,tensor_b.T.shape

(tensor([[ 27,  30,  33],
         [ 61,  68,  75],
         [ 95, 106, 117]]), torch.Size([3, 2]), torch.Size([2, 3]))

In [ ]:
torch.matmul(tensor_a.T,tensor_b),tensor_a.T.shape,tensor_b.shape

(tensor([[ 76, 103],
         [100, 136]]), torch.Size([2, 3]), torch.Size([3, 2]))

In [ ]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [ ]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [ ]:
# torch.mean(x),x.mean()

In [ ]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [ ]:
x.type(torch.float32).mean()

tensor(45.)

In [ ]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

In [ ]:
x.argmin(),torch.argmin(x)

(tensor(0), tensor(0))

In [ ]:
x.argmax(),torch.argmax(x)

(tensor(9), tensor(9))

In [ ]:
import torch
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x_reshaped = x.reshape(9,1)
x_reshaped,x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]), torch.Size([9, 1]))

In [ ]:
x_reshaped = x.reshape(3,3)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]), torch.Size([3, 3]))

In [ ]:
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
z,x

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
x[0] = 5
x,z

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [ ]:
z[0][0] = 0
x,z

(tensor([0., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[0., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [ ]:
z[:,0] = 5
x,z

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [ ]:
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked,x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([4, 9]))

In [ ]:
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked,x_stacked.shape

(tensor([[5., 5., 5., 5.],
         [2., 2., 2., 2.],
         [3., 3., 3., 3.],
         [4., 4., 4., 4.],
         [5., 5., 5., 5.],
         [6., 6., 6., 6.],
         [7., 7., 7., 7.],
         [8., 8., 8., 8.],
         [9., 9., 9., 9.]]), torch.Size([9, 4]))

In [ ]:
x_stacked = torch.stack([x,x,x,x],dim=-2)
x_stacked,x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([4, 9]))

In [ ]:
x_reshaped = x_reshaped.reshape(1,9)

In [ ]:
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_reshaped.squeeze(),x_reshaped.squeeze().shape,x_reshaped.shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 torch.Size([9]),
 torch.Size([1, 9]))

In [ ]:
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_squeezed.squeeze(),x_squeezed.squeeze().shape

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
torch.arange(1,10,3).squeeze()

tensor([1, 4, 7])

In [ ]:
x.unsqueeze(dim=0)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_original = torch.rand(size=(224,224,3))

In [ ]:
x_permuted = x_original.permute(2,0,1)
x_permuted,x_permuted.shape,x_original,x_original.shape

(tensor([[[5.0756e-01, 9.8644e-01, 4.3391e-01,  ..., 8.7058e-01,
           8.3675e-01, 6.5409e-01],
          [2.1796e-01, 8.8855e-02, 4.4255e-02,  ..., 2.7282e-01,
           3.8015e-01, 4.0137e-01],
          [6.1243e-01, 8.5327e-01, 6.7266e-01,  ..., 8.3364e-01,
           4.6588e-03, 4.7002e-01],
          ...,
          [2.2915e-01, 4.9948e-01, 1.7157e-01,  ..., 1.3873e-01,
           3.9733e-01, 1.8428e-01],
          [7.6453e-01, 6.5489e-01, 4.3577e-02,  ..., 8.4229e-01,
           1.7366e-01, 7.3275e-01],
          [3.6174e-01, 5.0870e-01, 6.9703e-01,  ..., 3.7338e-01,
           8.4907e-01, 5.8606e-01]],
 
         [[8.8157e-01, 5.5348e-02, 7.6038e-01,  ..., 8.7476e-01,
           4.2718e-01, 2.9297e-01],
          [2.4695e-01, 5.3512e-01, 2.0062e-01,  ..., 8.3568e-01,
           1.7150e-01, 6.3581e-01],
          [9.8352e-01, 8.6639e-01, 8.9624e-01,  ..., 3.3817e-01,
           6.8674e-01, 3.9055e-01],
          ...,
          [6.8408e-01, 8.5045e-02, 6.2508e-01,  ..., 5.217

In [ ]:
x = torch.tensor([[[1,2,3],
                   [4,5,6],
                   [7,8,9]]])

In [ ]:
x.shape

torch.Size([1, 3, 3])

In [ ]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
x[0][0]

tensor([1, 2, 3])

In [ ]:
x[0,0]

tensor([1, 2, 3])

In [ ]:
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
x[0][0][0]

tensor(1)

In [ ]:
x[0][2][2]

tensor(9)

In [ ]:
x[:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[:,:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
x[:,:1,:]

tensor([[[1, 2, 3]]])

In [ ]:
x[:,:,1:2]

tensor([[[2],
         [5],
         [8]]])

In [ ]:
x[:,:,2:3]

tensor([[[3],
         [6],
         [9]]])

In [ ]:
import torch
import numpy as np

In [ ]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
# tensor = torch.from_numpy(array).type(torch.float32)
array,array.shape,tensor,tensor.shape

(array([1., 2., 3., 4., 5., 6., 7.]),
 (7,),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 torch.Size([7]))

In [ ]:
array = array +1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor.dtype

torch.float32

In [ ]:
tensor = tensor +1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
import torch

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.9929, 0.7514, 0.9737, 0.7998],
        [0.9490, 0.2874, 0.6946, 0.3603],
        [0.6519, 0.3390, 0.2455, 0.1508]])
tensor([[0.7562, 0.7192, 0.0268, 0.3800],
        [0.7396, 0.8044, 0.8119, 0.2402],
        [0.6899, 0.4018, 0.4481, 0.2954]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)

random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
!nvidia-smi

Wed Jan 18 04:51:30 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   69C    P0    32W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

In [ ]:
tensor = torch.tensor([1,2,3])

print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
tensor = torch.tensor([1,2,3],device="cuda")
tensor,tensor.device

(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [ ]:
tensor = torch.tensor([1,2,3])
tensor,tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')